### PR TITLE
Handle Track Changes

### LINKED ISSUE #63: Disable track changes when inserting/editing citations
See https://api.libreoffice.org/docs/idl/ref/servicecom_1_1sun_1_1star_1_1text_1_1GenericTextDocument.html#a6649fa1a4963f78b9d70a85edef770e4 for API docs

### PR DESCRIPTION
**Pull request by raffaem**
Disable Track Changes before inserting citation, then re-enables it.
Fix #63.

### CODE REVIEW

**Comment by adomasven** [comment]
Thanks, this is great. One things that I'm worried about is that this code might throw and prevent operations that would otherwise function, so it would be good to wrap these in a catch and use `debugPrint()` to print whatever error is thrown. That prints to LibreOffice console and is outside the common process of troubleshooting for Zotero bugs, but we have no way to print to Zotero console on issue in LibreOffice plugin code and that's better than nothing. If somebody finds some edge-case on this code we can later fix it, without breaking the workflow for those users.

Also I'm testing this with LibreOffice 7.2 and it doesn't seem to do anything. Does this work for you? How are you testing and with what version?

**Comment by raffaem** [comment]
> Also I'm testing this with LibreOffice 7.2 and it doesn't seem to do anything. Does this work for you? How are you testing and with what version?

What does it mean doesn't seem to do anything?

Doesn't it disable Track Changes when you click Add/Edit Citation, and then re-enables them after you insert the citation or close the citation dialog?

I have:
Version: 7.3.5.2 / LibreOffice Community
Build ID: 184fe81b8c8c30d8b5082578aee2fed2ea847c01
CPU threads: 12; OS: Linux 5.18; UI render: default; VCL: gtk3
Locale: en-US (en_US.UTF-8); UI: en-US
Calc: threaded
on Fedora Workstation 36.

**Comment by adomasven** [comment]
Ok, I changed the version number on the extension to make sure I'm getting it reinstalled properly in LO and now it works. Sorry!

**Comment by raffaem** [comment]
ok.

Where do I find an example of the try/catch clause that you want?

The only instances of `debugPrint()` I have found in the entire extension are these:
```
$ grep "debugPrint" *
CommServer.java:					//ZoteroOpenOfficeIntegrationImpl.debugPrint("Writing "+new String(payload));
ZoteroOpenOfficeIntegrationImpl.java:	public static void debugPrint(String msg) {
ZoteroOpenOfficeIntegrationImpl.java:		debugPrint("Service initialized");
ZoteroOpenOfficeIntegrationImpl.java:				debugPrint("Activating window");
ZoteroOpenOfficeIntegrationImpl.java:		debugPrint("Executing "+command);
```

**Comment by adomasven** [comment]
> Where do I find an example of the try/catch clause that you want?

A catch [like this](https://github.com/zotero/zotero-libreoffice-integration/blob/50a4b4fc05e5a781eb3994670eb36049784068d1/build/source/org/zotero/integration/ooo/comp/Comm.java#L65-L68) is actually probably what we want.

**Comment by raffaem** [comment]
Is the `isRecordChanges` right to hold whether `recordChanges` has been initialized? Or is there a way to set `recordChanges` to NULL? I'm not used to Java.

**Comment by adomasven** [comment]
> Or is there a way to set `recordChanges` to NULL? I'm not used to Java.

Java is not my primary language either, but there's a [difference between `Boolean` and `boolean`](https://stackoverflow.com/questions/6226290/default-value-of-boolean-and-boolean-in-java). `Boolean` is nullable, since it's an Object internally, whereas `boolean` is a proper primitive.

Either way, I think you can do this with a single boolean variable and simplify the code. See how we do this in the Word plugin:
https://github.com/zotero/zotero-word-for-windows-integration/blob/master/build/zoteroWinWordIntegration/document.cpp#L186-L196
https://github.com/zotero/zotero-word-for-windows-integration/blob/master/build/zoteroWinWordIntegration/document.cpp#L1092-L1095

Also you need to move the code that checks for tracked changes into the `getDocument()` function.

**Comment by raffaem** [comment]
> Also you need to move the code that checks for tracked changes into the getDocument() function.

I didn't get that.

Are you referring to the code that *saves* the state of tracked changes?

Why?

The user can turn track changes on and off. So we want to get the state just before we visualize the box to insert a citation, no?

**Comment by raffaem** [comment]
Unless I'm blind there is no `getDocument()` function?
image

**Comment by adomasven** [comment]
> I didn't get that.
> 
> Are you referring to the code that _saves_ the state of tracked changes?
>
> Why?

Because Zotero does other stuff. If you go into document preferences and change a citation style all citations are rewritten. If you use Insert Note, it inserts text first, then may or may not call `insertField()` multiple times. Track changes should not be enabled for any of those operations. `getDocument()` is the location where we prepare the document for modifications with Zotero. And yeah, sorry, `getDocument()` is the generic comm message, this would be the `Document()` constructor in Document.java. Perhaps an even more appropriate way handle this would be in something like `ensureUndoContext()`, which is called before any write operation on the document. That would also mean track changes is not disabled while citation dialog is being shown. Although you should rename that function to `prepareDocumentForEditing()`.

**Comment by raffaem** [comment]
I did it, but `prepareDocumentForEditing` is called multiple times by clicking add/edit citation, so track changes is indeed disabled while citation dialog is being shown.

**Comment by raffaem** [comment]
> > I did it, but prepareDocumentForEditing is called multiple times by clicking add/edit citation, so track changes is indeed disabled while citation dialog is being shown.
> 
> Yeah, I guess that is true, since `insertField()` is called before showing the citation dialog. We can adjust this further later if necessary. Either way, thanks for this PR!

[You're welcome!](https://www.youtube.com/watch?v=79DijItQXMM)

**Pull request merged**
