### PR TITLE
Improved symlink_sdk script to work with WSL

### PR DESCRIPTION
**Pull request by otjura**
Added check to see if system is actually WSL.
Added default LibreOffice install path for WSL.
Fixed symlinking to allow spaces in paths.
Copy SDK folder in Windows because links don't work here.

### CODE REVIEW

**Comment by adomasven** [comment]
The JDK update would have to go into a separate PR, but you would also have to justify why the change is needed/useful? Wouldn't that just break backwards compatibility (possibly a non-issue since 1.5 is ancient, but we also would rather not fix what isn't broken).

We could merge the first commit if you force-push the branch and remove the second one.

**Comment by otjura** [comment]
User would have to go out of his way to get the previously targeted 1.5 version, then use that software which hasn't been supported for over 10 years. More importantly old build apparently only worked with Oracle JDK because I couldn't install it in my LibreOffice which is why I'm doing this in the first place. It was a broken extension in the current Java environment. I'm surprised I fixed it so quickly which is why it ended in this pull request, my bad, doing git push without considering this.

I'm not sure what exactly you want me to do. Walk me through it.

**Comment by adomasven** [comment]
> User would have to go out of his way to get the previously targeted 1.5 version, then use that software which hasn't been supported for over 10 years.

That is not the case. Oracle JRE is backwards compatible and the current build works with the newest versions of Java. This software is in use by thousands of users around the world with various setups and all changes have to be done cautiously.

> More importantly old build apparently only worked with Oracle JDK because I couldn't install it in my LibreOffice which is why I'm doing this in the first place. It was a broken extension in the current Java environment.

The current build certainly installs and works with OpenJDK 8 and 11 on Ubuntu. I haven't had a chance to test on WSL, but it is not out of the question that something about that setup could cause problems. Although a setup of LibreOffice on WSL shouldn't be required -- you can install and use LO on Windows directly -- and as such we'd rather not change our build settings risking breaking the extension for some old Zotero users to accommodate WSL LO installs.

> I'm not sure what exactly you want me to do. Walk me through it.

If you want to keep your latest OpenJDK commit you would have to checkout the current branch HEAD somewhere else, e.g.:
```git checkout -b openjdk-1.8-build```
Then checkout the original branch and reset the HEAD up by one commit and force-push the branch:
```
git checkout master
git reset --hard HEAD^
git push -f
```

**Comment by otjura** [comment]
I only use WSL to build this thing while in Windows, with LibreOffice Windows installation to source libreoffice sdk files from. I'm not running LibreOffice on WSL. I had to fix tooling first to fix the main issue which was plugin not working.

Zotero plugin as it is now does not work on Windows that is not running Oracle JRE. If you select to install LibreOffice plugin from current Zotero as advertised, it doesn't work. It doesn't recognise that LibreOffice or system actually has Java running in it and it's not only my setup, it's a lot of people. This problem is a major issue. https://www.google.com/search?q=zotero+libreoffice+integration+does+not+install

Thanks for git advice.

**Comment by adomasven** [comment]
> Zotero plugin as it is now does not work on Windows that is not running Oracle JRE. If you select to install LibreOffice plugin from current Zotero as advertised, it doesn't work. It doesn't recognise that LibreOffice or system actually has Java running in it and it's not only my setup, it's a lot of people.

I'm not entirely sure that you're not mixing things up. For the record the Zotero plugin definitely works with both Oracle and OpenJDK implementations of JRE on Windows. I have just tested with OpenJDK 14 as well as Oracle JRE 12. The Zotero automatic installer, however, might fail in certain cases, but that's a completely separate issue. For the record on Windows the Zotero LO plugin installer checks the Registry for default Oracle JRE installation keys. At least the current general release of OpenJDK 14 comes without any installer and thus no registry keys exist if you use it with LibreOffice. Thus to install the plugin into LO you'd have to use the [manual installation](https://www.zotero.org/support/word_processor_plugin_manual_installation) instructions. The number of people running OpenJDK on Windows is an incredible minority (in fact I cannot remember seeing anyone ask questions about OpenJDK on Windows with LibreOffice over the past 2 years on Zotero Forums or on Github), which is why this is not a concern for us.

If we were looking to improve the installer for WIndows, we'd probably try to change the Zotero LO plugin installer to check whether LibreOffice has a JRE assigned to it rather than just check for a JRE installation, but once again, that is of trivial concern as things stand now.

I'm going to merge your PR now. Thanks for that! If you have plugin installation related issues we can continue the discussion on [Zotero forums](forums.zotero.org) if you create a thread there. If you have development related questions then please post on the [zotero-dev mailinglist](https://groups.google.com/forum/#!forum/zotero-dev)

**Pull request merged**
